label.titulo.pagina.consulta = Agendas Cadastradas
label.titulo.pagina.cadastro = Cadastro de Agenda
label.agendas = Agendas
label.nova.agenda = Nova Agenda
label.periodo = Per\u00EDodo
label.periodo.manha = Manh\u00E3
label.periodo.tarde = Tarde
label.periodo.ambos = Ambos