label.titulo.pagina.consulta = Compromissos Cadastrados
label.titulo.pagina.cadastro = Cadastro de Compromisso
label.funcionario = Funcion\u00E1rio
label.agenda = Agenda
label.data = Data
label.hora = Hora
label.compromissos = Compromissos
label.novo.compromisso = Novo Compromisso