label.funcionarios = Funcion\u00E1rios
label.agendas = Agendas
label.compromissos = Compromissos
label.relatorio.compromissos = Relat\u00F3rio de Compromissos
label.titulo.pagina = Relat\u00F3rio de Compromissos
label.data.inicial = Data Inicial
label.data.final = Data Final
label.gerar = Gerar
label.exportar.excel = Exportar Excel
label.codigo.funcionario = C\u00F3digo Funcion\u00E1rio
label.nome.funcionario = Nome Funcion\u00E1rio
label.codigo.agenda = C\u00F3digo Agenda
label.nome.agenda = Nome Agenda
label.data = Data
label.hora = Hora